# eletricheater:
#   - location1:
#       position: [0.21, 0.7, 0.01]
#       orientation: [0.0, 0.0, 0.0, 1.0]

drum:
  - location1:
        position: [0.0, 0.0, 0.35]
        orientation: [0.0, 0.0, 0.0, 1.0]
        trajectory: ["circle", 0.14, 0.0, 6.28, 30]

case:
  - location1:
        position: [0.23, -0.25, 0.26]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location2:
        position: [-0.23, -0.25, 0.26]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location3:
        position: [-0.23, -0.25, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]

  - location4:
        position: [0.23, -0.25, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]

  - location5:
        position: [0.23, -0.25, 0.26]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

firecabinet:
  - location1:
        position: [0.458, -0.22, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]

  - location2:
        position: [0.458, -0.22, 0.685]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location3:
        position: [-0.19, -0.22, 0.685]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location4:
        position: [-0.19, -0.22, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]

  - location5:
        position: [-0.21, -0.22, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]

  - location6:
        position: [-0.21, -0.22, 0.685]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location7:
        position: [-0.458, -0.22, 0.685]
        orientation: [0.0, -1.0, 0.0, 1.0]
        trajectory: ["normal"]

  - location8:
        position: [-0.458, -0.22, 0.05]
        orientation: [0.0, -0.3, 0.0, 1.0]
        trajectory: ["normal"]